#!/usr/bin/env python3
"""Update the SF CLI compatibility record and regenerate the public table.

Single source of truth is compatibility.json (Internal-only). The rendered
docs/compatibility.md is what gets published to CairnCI-Public.

Usage:
  update-compat.py --version 2.143.0 --node 22 --status validated \
      --sgd 6.31.0 --date 2026-07-21
  update-compat.py --version 2.143.0 --node 22 --status failing \
      --date 2026-07-21 --reason "markAsUncloneable is not a function"
"""
import argparse
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "compatibility.json")
MD_PATH = os.path.join(ROOT, "docs", "compatibility.md")


def version_key(v):
    # Sort semver-ish "2.143.0" numerically, newest first. Non-numeric parts
    # fall back to 0 so a malformed key can't crash the render.
    parts = []
    for p in v.split("."):
        try:
            parts.append(int(p))
        except ValueError:
            parts.append(0)
    return parts


def load():
    if os.path.exists(JSON_PATH):
        with open(JSON_PATH) as f:
            return json.load(f)
    return {"results": {}}


def render(data):
    rows = []
    for ver in sorted(data["results"], key=version_key, reverse=True):
        e = data["results"][ver]
        if e["status"] == "validated":
            status = "✅ validated"
        else:
            status = "❌ failing"
        sgd = e.get("sgd", "—")
        note = ""
        if e["status"] == "failing" and e.get("reason"):
            # Keep the reason on one line; escape pipes so the table stays intact.
            note = " <br><sub>" + e["reason"].replace("|", "\\|") + "</sub>"
        rows.append(
            f"| `{ver}` | {e.get('node', '—')} | {sgd} | {status}{note} | {e.get('date', '—')} |"
        )

    base = "https://github.com/Fossiltalk/CairnCI-Internal/actions/workflows"
    # Pinned-toolchain health (integration-permutations runs the pinned
    # CLI/Node/sgd against the org) and the latest-release probe.
    pinned_badge = (
        f"**Pinned toolchain:** "
        f"[![Integration]({base}/integration-permutations.yml/badge.svg)]"
        f"({base}/integration-permutations.yml)"
    )
    probe_badge = (
        f"**Latest `@salesforce/cli`:** "
        f"[![SF CLI Compatibility Probe]({base}/sf-cli-compat-probe.yml/badge.svg)]"
        f"({base}/sf-cli-compat-probe.yml)"
    )
    lines = [
        "# SF CLI Compatibility",
        "",
        pinned_badge + " &nbsp; " + probe_badge,
        "",
        "Which `@salesforce/cli` versions CairnCI has validated end-to-end. Each",
        "row was exercised by CairnCI's integration test (a delta and a",
        "full-branch permutation) against a real Salesforce org on the date shown,",
        "using the listed Node.js version. Pin to a `✅ validated` version.",
        "",
        "> Generated by the SF CLI Compatibility Probe — do not edit by hand.",
        "",
        "| `@salesforce/cli` | Node | `sfdx-git-delta` | Status | Validated on |",
        "|---|---|---|---|---|",
    ]
    lines.extend(rows)
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--node", required=True)
    ap.add_argument("--status", required=True, choices=["validated", "failing"])
    ap.add_argument("--date", required=True)
    ap.add_argument("--sgd", default=None)
    ap.add_argument("--reason", default=None)
    args = ap.parse_args()

    data = load()
    data.setdefault("results", {})

    entry = {"status": args.status, "node": args.node, "date": args.date}
    if args.sgd:
        entry["sgd"] = args.sgd
    if args.status == "failing" and args.reason:
        entry["reason"] = args.reason
    data["results"][args.version] = entry

    with open(JSON_PATH, "w") as f:
        json.dump(data, f, indent=2, sort_keys=True)
        f.write("\n")

    os.makedirs(os.path.dirname(MD_PATH), exist_ok=True)
    with open(MD_PATH, "w") as f:
        f.write(render(data))

    print(f"Recorded {args.version}: {args.status} (node {args.node}) on {args.date}")


if __name__ == "__main__":
    main()
